//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.CixGetLegalPerson {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CixGetLegalPerson.GetLegalPersonInfoDBPortType")]
    public interface GetLegalPersonInfoDBPortType {
        
        // CODEGEN: Parameter 'InquiryByNationalCodeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICiiService/InquiryByNationalCode", ReplyAction="//tempuri.org/ICiiService/InquiryByNationalCodeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SRL.CixGetLegalPerson.InquiryByNationalCodeResponse InquiryByNationalCode(SRL.CixGetLegalPerson.InquiryByNationalCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICiiService/InquiryByNationalCode", ReplyAction="//tempuri.org/ICiiService/InquiryByNationalCodeResponse")]
        System.Threading.Tasks.Task<SRL.CixGetLegalPerson.InquiryByNationalCodeResponse> InquiryByNationalCodeAsync(SRL.CixGetLegalPerson.InquiryByNationalCodeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PDN.CII.ViewModels")]
    public partial class Parameter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nationalCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string NationalCode {
            get {
                return this.nationalCodeField;
            }
            set {
                this.nationalCodeField = value;
                this.RaisePropertyChanged("NationalCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PDN.CII.ViewModels")]
    public partial class Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private Result[] branchListField;
        
        private string breakUpDateField;
        
        private string establishmentDateField;
        
        private string followUpNoField;
        
        private bool isBranchField;
        
        private bool isBranchFieldSpecified;
        
        private bool isBreakUpField;
        
        private bool isBreakUpFieldSpecified;
        
        private bool isDbResultField;
        
        private bool isDbResultFieldSpecified;
        
        private bool isSettleField;
        
        private bool isSettleFieldSpecified;
        
        private string legalPersonTypeField;
        
        private string messageField;
        
        private string nameField;
        
        private string nationalCodeField;
        
        private Result parentLegalPersonField;
        
        private string postCodeField;
        
        private string registerDateField;
        
        private string registerNumberField;
        
        private string registerUnitField;
        
        private string residencyField;
        
        private string settleDateField;
        
        private string stateField;
        
        private bool successfulField;
        
        private bool successfulFieldSpecified;
        
        private int userIdField;
        
        private bool userIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        public Result[] BranchList {
            get {
                return this.branchListField;
            }
            set {
                this.branchListField = value;
                this.RaisePropertyChanged("BranchList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string BreakUpDate {
            get {
                return this.breakUpDateField;
            }
            set {
                this.breakUpDateField = value;
                this.RaisePropertyChanged("BreakUpDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string EstablishmentDate {
            get {
                return this.establishmentDateField;
            }
            set {
                this.establishmentDateField = value;
                this.RaisePropertyChanged("EstablishmentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string FollowUpNo {
            get {
                return this.followUpNoField;
            }
            set {
                this.followUpNoField = value;
                this.RaisePropertyChanged("FollowUpNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool IsBranch {
            get {
                return this.isBranchField;
            }
            set {
                this.isBranchField = value;
                this.RaisePropertyChanged("IsBranch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsBranchSpecified {
            get {
                return this.isBranchFieldSpecified;
            }
            set {
                this.isBranchFieldSpecified = value;
                this.RaisePropertyChanged("IsBranchSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool IsBreakUp {
            get {
                return this.isBreakUpField;
            }
            set {
                this.isBreakUpField = value;
                this.RaisePropertyChanged("IsBreakUp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsBreakUpSpecified {
            get {
                return this.isBreakUpFieldSpecified;
            }
            set {
                this.isBreakUpFieldSpecified = value;
                this.RaisePropertyChanged("IsBreakUpSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsDbResult {
            get {
                return this.isDbResultField;
            }
            set {
                this.isDbResultField = value;
                this.RaisePropertyChanged("IsDbResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsDbResultSpecified {
            get {
                return this.isDbResultFieldSpecified;
            }
            set {
                this.isDbResultFieldSpecified = value;
                this.RaisePropertyChanged("IsDbResultSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool IsSettle {
            get {
                return this.isSettleField;
            }
            set {
                this.isSettleField = value;
                this.RaisePropertyChanged("IsSettle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsSettleSpecified {
            get {
                return this.isSettleFieldSpecified;
            }
            set {
                this.isSettleFieldSpecified = value;
                this.RaisePropertyChanged("IsSettleSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string LegalPersonType {
            get {
                return this.legalPersonTypeField;
            }
            set {
                this.legalPersonTypeField = value;
                this.RaisePropertyChanged("LegalPersonType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string NationalCode {
            get {
                return this.nationalCodeField;
            }
            set {
                this.nationalCodeField = value;
                this.RaisePropertyChanged("NationalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public Result ParentLegalPerson {
            get {
                return this.parentLegalPersonField;
            }
            set {
                this.parentLegalPersonField = value;
                this.RaisePropertyChanged("ParentLegalPerson");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
                this.RaisePropertyChanged("PostCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string RegisterDate {
            get {
                return this.registerDateField;
            }
            set {
                this.registerDateField = value;
                this.RaisePropertyChanged("RegisterDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string RegisterNumber {
            get {
                return this.registerNumberField;
            }
            set {
                this.registerNumberField = value;
                this.RaisePropertyChanged("RegisterNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string RegisterUnit {
            get {
                return this.registerUnitField;
            }
            set {
                this.registerUnitField = value;
                this.RaisePropertyChanged("RegisterUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string Residency {
            get {
                return this.residencyField;
            }
            set {
                this.residencyField = value;
                this.RaisePropertyChanged("Residency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string SettleDate {
            get {
                return this.settleDateField;
            }
            set {
                this.settleDateField = value;
                this.RaisePropertyChanged("SettleDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool Successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
                this.RaisePropertyChanged("Successful");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessfulSpecified {
            get {
                return this.successfulFieldSpecified;
            }
            set {
                this.successfulFieldSpecified = value;
                this.RaisePropertyChanged("SuccessfulSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UserIdSpecified {
            get {
                return this.userIdFieldSpecified;
            }
            set {
                this.userIdFieldSpecified = value;
                this.RaisePropertyChanged("UserIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InquiryByNationalCode", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InquiryByNationalCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SRL.CixGetLegalPerson.Parameter parameter;
        
        public InquiryByNationalCodeRequest() {
        }
        
        public InquiryByNationalCodeRequest(SRL.CixGetLegalPerson.Parameter parameter) {
            this.parameter = parameter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InquiryByNationalCodeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InquiryByNationalCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SRL.CixGetLegalPerson.Result InquiryByNationalCodeResult;
        
        public InquiryByNationalCodeResponse() {
        }
        
        public InquiryByNationalCodeResponse(SRL.CixGetLegalPerson.Result InquiryByNationalCodeResult) {
            this.InquiryByNationalCodeResult = InquiryByNationalCodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetLegalPersonInfoDBPortTypeChannel : SRL.CixGetLegalPerson.GetLegalPersonInfoDBPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLegalPersonInfoDBPortTypeClient : System.ServiceModel.ClientBase<SRL.CixGetLegalPerson.GetLegalPersonInfoDBPortType>, SRL.CixGetLegalPerson.GetLegalPersonInfoDBPortType {
        
        public GetLegalPersonInfoDBPortTypeClient() {
        }
        
        public GetLegalPersonInfoDBPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetLegalPersonInfoDBPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetLegalPersonInfoDBPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetLegalPersonInfoDBPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SRL.CixGetLegalPerson.InquiryByNationalCodeResponse SRL.CixGetLegalPerson.GetLegalPersonInfoDBPortType.InquiryByNationalCode(SRL.CixGetLegalPerson.InquiryByNationalCodeRequest request) {
            return base.Channel.InquiryByNationalCode(request);
        }
        
        public SRL.CixGetLegalPerson.Result InquiryByNationalCode(SRL.CixGetLegalPerson.Parameter parameter) {
            SRL.CixGetLegalPerson.InquiryByNationalCodeRequest inValue = new SRL.CixGetLegalPerson.InquiryByNationalCodeRequest();
            inValue.parameter = parameter;
            SRL.CixGetLegalPerson.InquiryByNationalCodeResponse retVal = ((SRL.CixGetLegalPerson.GetLegalPersonInfoDBPortType)(this)).InquiryByNationalCode(inValue);
            return retVal.InquiryByNationalCodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SRL.CixGetLegalPerson.InquiryByNationalCodeResponse> SRL.CixGetLegalPerson.GetLegalPersonInfoDBPortType.InquiryByNationalCodeAsync(SRL.CixGetLegalPerson.InquiryByNationalCodeRequest request) {
            return base.Channel.InquiryByNationalCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SRL.CixGetLegalPerson.InquiryByNationalCodeResponse> InquiryByNationalCodeAsync(SRL.CixGetLegalPerson.Parameter parameter) {
            SRL.CixGetLegalPerson.InquiryByNationalCodeRequest inValue = new SRL.CixGetLegalPerson.InquiryByNationalCodeRequest();
            inValue.parameter = parameter;
            return ((SRL.CixGetLegalPerson.GetLegalPersonInfoDBPortType)(this)).InquiryByNationalCodeAsync(inValue);
        }
    }
}
