//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.CIXGetAddressByPostcode {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CIXGetAddressByPostcode.GetAddressByPostCodePortType")]
    public interface GetAddressByPostCodePortType {
        
        // CODEGEN: Parameter 'GetAddressByPostcodeResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetAddressByPostcode", ReplyAction="//tempuri.org/IPostCode/GetAddressByPostcodeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Result))]
        SRL.CIXGetAddressByPostcode.GetAddressByPostcodeResponse GetAddressByPostcode(SRL.CIXGetAddressByPostcode.GetAddressByPostcodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetAddressByPostcode", ReplyAction="//tempuri.org/IPostCode/GetAddressByPostcodeResponse")]
        System.Threading.Tasks.Task<SRL.CIXGetAddressByPostcode.GetAddressByPostcodeResponse> GetAddressByPostcodeAsync(SRL.CIXGetAddressByPostcode.GetAddressByPostcodeRequest request);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CertificateResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhoneAddressResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    public partial class AddressResult : Result {
        
        private string avenueField;
        
        private string buildingNameField;
        
        private string descriptionField;
        
        private string floorNoField;
        
        private double houseNoField;
        
        private bool houseNoFieldSpecified;
        
        private string locationField;
        
        private string locationCodeField;
        
        private string locationTypeField;
        
        private string parishField;
        
        private string postCodeField;
        
        private string preAvenueField;
        
        private string sideFloorField;
        
        private string stateField;
        
        private string townShipField;
        
        private string villageField;
        
        private string zoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Avenue {
            get {
                return this.avenueField;
            }
            set {
                this.avenueField = value;
                this.RaisePropertyChanged("Avenue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string BuildingName {
            get {
                return this.buildingNameField;
            }
            set {
                this.buildingNameField = value;
                this.RaisePropertyChanged("BuildingName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string FloorNo {
            get {
                return this.floorNoField;
            }
            set {
                this.floorNoField = value;
                this.RaisePropertyChanged("FloorNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double HouseNo {
            get {
                return this.houseNoField;
            }
            set {
                this.houseNoField = value;
                this.RaisePropertyChanged("HouseNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HouseNoSpecified {
            get {
                return this.houseNoFieldSpecified;
            }
            set {
                this.houseNoFieldSpecified = value;
                this.RaisePropertyChanged("HouseNoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string LocationCode {
            get {
                return this.locationCodeField;
            }
            set {
                this.locationCodeField = value;
                this.RaisePropertyChanged("LocationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string LocationType {
            get {
                return this.locationTypeField;
            }
            set {
                this.locationTypeField = value;
                this.RaisePropertyChanged("LocationType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string Parish {
            get {
                return this.parishField;
            }
            set {
                this.parishField = value;
                this.RaisePropertyChanged("Parish");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string PostCode {
            get {
                return this.postCodeField;
            }
            set {
                this.postCodeField = value;
                this.RaisePropertyChanged("PostCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string PreAvenue {
            get {
                return this.preAvenueField;
            }
            set {
                this.preAvenueField = value;
                this.RaisePropertyChanged("PreAvenue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string SideFloor {
            get {
                return this.sideFloorField;
            }
            set {
                this.sideFloorField = value;
                this.RaisePropertyChanged("SideFloor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string TownShip {
            get {
                return this.townShipField;
            }
            set {
                this.townShipField = value;
                this.RaisePropertyChanged("TownShip");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string Village {
            get {
                return this.villageField;
            }
            set {
                this.villageField = value;
                this.RaisePropertyChanged("Village");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string Zone {
            get {
                return this.zoneField;
            }
            set {
                this.zoneField = value;
                this.RaisePropertyChanged("Zone");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WorkshopResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActivityCodeResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BooleanResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PositionResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhoneResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StringResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AddressResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CertificateResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DataResult))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PhoneAddressResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    public partial class Result : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorCodeSpecified {
            get {
                return this.errorCodeFieldSpecified;
            }
            set {
                this.errorCodeFieldSpecified = value;
                this.RaisePropertyChanged("ErrorCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    public partial class WorkshopResult : Result {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    public partial class ActivityCodeResult : Result {
        
        private string typeCodeField;
        
        private string typeCode2Field;
        
        private string typeCode3Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string TypeCode {
            get {
                return this.typeCodeField;
            }
            set {
                this.typeCodeField = value;
                this.RaisePropertyChanged("TypeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string TypeCode2 {
            get {
                return this.typeCode2Field;
            }
            set {
                this.typeCode2Field = value;
                this.RaisePropertyChanged("TypeCode2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string TypeCode3 {
            get {
                return this.typeCode3Field;
            }
            set {
                this.typeCode3Field = value;
                this.RaisePropertyChanged("TypeCode3");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    public partial class BooleanResult : Result {
        
        private bool valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
                this.RaisePropertyChanged("ValueSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    public partial class PositionResult : Result {
        
        private double latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private double longitudeField;
        
        private bool longitudeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
                this.RaisePropertyChanged("LatitudeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
                this.RaisePropertyChanged("LongitudeSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    public partial class PhoneResult : Result {
        
        private string phoneNoField;
        
        private string prePhoneNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string PhoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
                this.RaisePropertyChanged("PhoneNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string PrePhoneNo {
            get {
                return this.prePhoneNoField;
            }
            set {
                this.prePhoneNoField = value;
                this.RaisePropertyChanged("PrePhoneNo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    public partial class StringResult : Result {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    public partial class CertificateResult : AddressResult {
        
        private string certificateNoField;
        
        private string certificateUrlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string CertificateNo {
            get {
                return this.certificateNoField;
            }
            set {
                this.certificateNoField = value;
                this.RaisePropertyChanged("CertificateNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string CertificateUrl {
            get {
                return this.certificateUrlField;
            }
            set {
                this.certificateUrlField = value;
                this.RaisePropertyChanged("CertificateUrl");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    public partial class DataResult : AddressResult {
        
        private double latitudeField;
        
        private bool latitudeFieldSpecified;
        
        private double longitudeField;
        
        private bool longitudeFieldSpecified;
        
        private string phoneNoField;
        
        private string prePhoneNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
                this.RaisePropertyChanged("Latitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatitudeSpecified {
            get {
                return this.latitudeFieldSpecified;
            }
            set {
                this.latitudeFieldSpecified = value;
                this.RaisePropertyChanged("LatitudeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
                this.RaisePropertyChanged("Longitude");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LongitudeSpecified {
            get {
                return this.longitudeFieldSpecified;
            }
            set {
                this.longitudeFieldSpecified = value;
                this.RaisePropertyChanged("LongitudeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string PhoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
                this.RaisePropertyChanged("PhoneNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string PrePhoneNo {
            get {
                return this.prePhoneNoField;
            }
            set {
                this.prePhoneNoField = value;
                this.RaisePropertyChanged("PrePhoneNo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    public partial class PhoneAddressResult : AddressResult {
        
        private string phoneNoField;
        
        private string prePhoneNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string PhoneNo {
            get {
                return this.phoneNoField;
            }
            set {
                this.phoneNoField = value;
                this.RaisePropertyChanged("PhoneNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string PrePhoneNo {
            get {
                return this.prePhoneNoField;
            }
            set {
                this.prePhoneNoField = value;
                this.RaisePropertyChanged("PrePhoneNo");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAddressByPostcode", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAddressByPostcodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string messageHash;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string postcode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string regionCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string nodeCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string clientName;
        
        public GetAddressByPostcodeRequest() {
        }
        
        public GetAddressByPostcodeRequest(string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            this.messageHash = messageHash;
            this.postcode = postcode;
            this.regionCode = regionCode;
            this.nodeCode = nodeCode;
            this.clientName = clientName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAddressByPostcodeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAddressByPostcodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SRL.CIXGetAddressByPostcode.AddressResult GetAddressByPostcodeResult;
        
        public GetAddressByPostcodeResponse() {
        }
        
        public GetAddressByPostcodeResponse(SRL.CIXGetAddressByPostcode.AddressResult GetAddressByPostcodeResult) {
            this.GetAddressByPostcodeResult = GetAddressByPostcodeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetAddressByPostCodePortTypeChannel : SRL.CIXGetAddressByPostcode.GetAddressByPostCodePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAddressByPostCodePortTypeClient : System.ServiceModel.ClientBase<SRL.CIXGetAddressByPostcode.GetAddressByPostCodePortType>, SRL.CIXGetAddressByPostcode.GetAddressByPostCodePortType {
        
        public GetAddressByPostCodePortTypeClient() {
        }
        
        public GetAddressByPostCodePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetAddressByPostCodePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetAddressByPostCodePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetAddressByPostCodePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SRL.CIXGetAddressByPostcode.GetAddressByPostcodeResponse SRL.CIXGetAddressByPostcode.GetAddressByPostCodePortType.GetAddressByPostcode(SRL.CIXGetAddressByPostcode.GetAddressByPostcodeRequest request) {
            return base.Channel.GetAddressByPostcode(request);
        }
        
        public SRL.CIXGetAddressByPostcode.AddressResult GetAddressByPostcode(string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            SRL.CIXGetAddressByPostcode.GetAddressByPostcodeRequest inValue = new SRL.CIXGetAddressByPostcode.GetAddressByPostcodeRequest();
            inValue.messageHash = messageHash;
            inValue.postcode = postcode;
            inValue.regionCode = regionCode;
            inValue.nodeCode = nodeCode;
            inValue.clientName = clientName;
            SRL.CIXGetAddressByPostcode.GetAddressByPostcodeResponse retVal = ((SRL.CIXGetAddressByPostcode.GetAddressByPostCodePortType)(this)).GetAddressByPostcode(inValue);
            return retVal.GetAddressByPostcodeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SRL.CIXGetAddressByPostcode.GetAddressByPostcodeResponse> SRL.CIXGetAddressByPostcode.GetAddressByPostCodePortType.GetAddressByPostcodeAsync(SRL.CIXGetAddressByPostcode.GetAddressByPostcodeRequest request) {
            return base.Channel.GetAddressByPostcodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<SRL.CIXGetAddressByPostcode.GetAddressByPostcodeResponse> GetAddressByPostcodeAsync(string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            SRL.CIXGetAddressByPostcode.GetAddressByPostcodeRequest inValue = new SRL.CIXGetAddressByPostcode.GetAddressByPostcodeRequest();
            inValue.messageHash = messageHash;
            inValue.postcode = postcode;
            inValue.regionCode = regionCode;
            inValue.nodeCode = nodeCode;
            inValue.clientName = clientName;
            return ((SRL.CIXGetAddressByPostcode.GetAddressByPostCodePortType)(this)).GetAddressByPostcodeAsync(inValue);
        }
    }
}
