//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.SmsNtswService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsNtswService.SendSMSFromPortType")]
    public interface SendSMSFromPortType {
        
        // CODEGEN: Parameter 'UserName' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INTSWWebService/SendSMSFrom", ReplyAction="//tempuri.org/INTSWWebService/SendSMSFromResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SRL.SmsNtswService.SendSMSFromResponse SendSMSFrom(SRL.SmsNtswService.SendSMSFromRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INTSWWebService/SendSMSFrom", ReplyAction="//tempuri.org/INTSWWebService/SendSMSFromResponse")]
        System.Threading.Tasks.Task<SRL.SmsNtswService.SendSMSFromResponse> SendSMSFromAsync(SRL.SmsNtswService.SendSMSFromRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="CsOperationManagment.SendSMSFromInfo", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    public partial class CsOperationManagmentSendSMSFromInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fromField;
        
        private bool isResendField;
        
        private bool isResendFieldSpecified;
        
        private bool isSwitchField;
        
        private bool isSwitchFieldSpecified;
        
        private string messageField;
        
        private System.DateTime resendDurationField;
        
        private bool resendDurationFieldSpecified;
        
        private string toField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
                this.RaisePropertyChanged("From");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool IsResend {
            get {
                return this.isResendField;
            }
            set {
                this.isResendField = value;
                this.RaisePropertyChanged("IsResend");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsResendSpecified {
            get {
                return this.isResendFieldSpecified;
            }
            set {
                this.isResendFieldSpecified = value;
                this.RaisePropertyChanged("IsResendSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsSwitch {
            get {
                return this.isSwitchField;
            }
            set {
                this.isSwitchField = value;
                this.RaisePropertyChanged("IsSwitch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsSwitchSpecified {
            get {
                return this.isSwitchFieldSpecified;
            }
            set {
                this.isSwitchFieldSpecified = value;
                this.RaisePropertyChanged("IsSwitchSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime ResendDuration {
            get {
                return this.resendDurationField;
            }
            set {
                this.resendDurationField = value;
                this.RaisePropertyChanged("ResendDuration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResendDurationSpecified {
            get {
                return this.resendDurationFieldSpecified;
            }
            set {
                this.resendDurationFieldSpecified = value;
                this.RaisePropertyChanged("ResendDurationSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
                this.RaisePropertyChanged("To");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="CsOperationManagment.RequestAnswer", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    public partial class CsOperationManagmentRequestAnswer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long errorCodeField;
        
        private bool errorCodeFieldSpecified;
        
        private string errorMessageField;
        
        private long recIDField;
        
        private bool recIDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorCodeSpecified {
            get {
                return this.errorCodeFieldSpecified;
            }
            set {
                this.errorCodeFieldSpecified = value;
                this.RaisePropertyChanged("ErrorCodeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long RecID {
            get {
                return this.recIDField;
            }
            set {
                this.recIDField = value;
                this.RaisePropertyChanged("RecID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RecIDSpecified {
            get {
                return this.recIDFieldSpecified;
            }
            set {
                this.recIDFieldSpecified = value;
                this.RaisePropertyChanged("RecIDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSFrom", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSFromRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string UserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public SRL.SmsNtswService.CsOperationManagmentSendSMSFromInfo SmsFromInfo;
        
        public SendSMSFromRequest() {
        }
        
        public SendSMSFromRequest(string UserName, string Password, SRL.SmsNtswService.CsOperationManagmentSendSMSFromInfo SmsFromInfo) {
            this.UserName = UserName;
            this.Password = Password;
            this.SmsFromInfo = SmsFromInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendSMSFromResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SendSMSFromResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SRL.SmsNtswService.CsOperationManagmentRequestAnswer SendSMSFromResult;
        
        public SendSMSFromResponse() {
        }
        
        public SendSMSFromResponse(SRL.SmsNtswService.CsOperationManagmentRequestAnswer SendSMSFromResult) {
            this.SendSMSFromResult = SendSMSFromResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendSMSFromPortTypeChannel : SRL.SmsNtswService.SendSMSFromPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendSMSFromPortTypeClient : System.ServiceModel.ClientBase<SRL.SmsNtswService.SendSMSFromPortType>, SRL.SmsNtswService.SendSMSFromPortType {
        
        public SendSMSFromPortTypeClient() {
        }
        
        public SendSMSFromPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendSMSFromPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMSFromPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendSMSFromPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SRL.SmsNtswService.SendSMSFromResponse SRL.SmsNtswService.SendSMSFromPortType.SendSMSFrom(SRL.SmsNtswService.SendSMSFromRequest request) {
            return base.Channel.SendSMSFrom(request);
        }
        
        public SRL.SmsNtswService.CsOperationManagmentRequestAnswer SendSMSFrom(string UserName, string Password, SRL.SmsNtswService.CsOperationManagmentSendSMSFromInfo SmsFromInfo) {
            SRL.SmsNtswService.SendSMSFromRequest inValue = new SRL.SmsNtswService.SendSMSFromRequest();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.SmsFromInfo = SmsFromInfo;
            SRL.SmsNtswService.SendSMSFromResponse retVal = ((SRL.SmsNtswService.SendSMSFromPortType)(this)).SendSMSFrom(inValue);
            return retVal.SendSMSFromResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SRL.SmsNtswService.SendSMSFromResponse> SRL.SmsNtswService.SendSMSFromPortType.SendSMSFromAsync(SRL.SmsNtswService.SendSMSFromRequest request) {
            return base.Channel.SendSMSFromAsync(request);
        }
        
        public System.Threading.Tasks.Task<SRL.SmsNtswService.SendSMSFromResponse> SendSMSFromAsync(string UserName, string Password, SRL.SmsNtswService.CsOperationManagmentSendSMSFromInfo SmsFromInfo) {
            SRL.SmsNtswService.SendSMSFromRequest inValue = new SRL.SmsNtswService.SendSMSFromRequest();
            inValue.UserName = UserName;
            inValue.Password = Password;
            inValue.SmsFromInfo = SmsFromInfo;
            return ((SRL.SmsNtswService.SendSMSFromPortType)(this)).SendSMSFromAsync(inValue);
        }
    }
}
