//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRL.PostCodeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRL.PostCodeServiceReference.StringResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRL.PostCodeServiceReference.PhoneResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRL.PostCodeServiceReference.PositionResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRL.PostCodeServiceReference.BooleanResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRL.PostCodeServiceReference.ActivityCodeResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRL.PostCodeServiceReference.WorkshopResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRL.PostCodeServiceReference.AddressResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRL.PostCodeServiceReference.PhoneAddressResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRL.PostCodeServiceReference.DataResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRL.PostCodeServiceReference.CertificateResult))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((this.ErrorCodeField.Equals(value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StringResult", Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    [System.SerializableAttribute()]
    public partial class StringResult : SRL.PostCodeServiceReference.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneResult", Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    [System.SerializableAttribute()]
    public partial class PhoneResult : SRL.PostCodeServiceReference.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrePhoneNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrePhoneNo {
            get {
                return this.PrePhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrePhoneNoField, value) != true)) {
                    this.PrePhoneNoField = value;
                    this.RaisePropertyChanged("PrePhoneNo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PositionResult", Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    [System.SerializableAttribute()]
    public partial class PositionResult : SRL.PostCodeServiceReference.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BooleanResult", Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    [System.SerializableAttribute()]
    public partial class BooleanResult : SRL.PostCodeServiceReference.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Value {
            get {
                return this.ValueField;
            }
            set {
                if ((this.ValueField.Equals(value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivityCodeResult", Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    [System.SerializableAttribute()]
    public partial class ActivityCodeResult : SRL.PostCodeServiceReference.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeCode2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeCode3Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeCode {
            get {
                return this.TypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeCodeField, value) != true)) {
                    this.TypeCodeField = value;
                    this.RaisePropertyChanged("TypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeCode2 {
            get {
                return this.TypeCode2Field;
            }
            set {
                if ((object.ReferenceEquals(this.TypeCode2Field, value) != true)) {
                    this.TypeCode2Field = value;
                    this.RaisePropertyChanged("TypeCode2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TypeCode3 {
            get {
                return this.TypeCode3Field;
            }
            set {
                if ((object.ReferenceEquals(this.TypeCode3Field, value) != true)) {
                    this.TypeCode3Field = value;
                    this.RaisePropertyChanged("TypeCode3");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkshopResult", Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    [System.SerializableAttribute()]
    public partial class WorkshopResult : SRL.PostCodeServiceReference.Result {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressResult", Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRL.PostCodeServiceReference.PhoneAddressResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRL.PostCodeServiceReference.DataResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SRL.PostCodeServiceReference.CertificateResult))]
    public partial class AddressResult : SRL.PostCodeServiceReference.Result {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvenueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FloorNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HouseNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PostCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreAvenueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SideFloorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownShipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VillageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Avenue {
            get {
                return this.AvenueField;
            }
            set {
                if ((object.ReferenceEquals(this.AvenueField, value) != true)) {
                    this.AvenueField = value;
                    this.RaisePropertyChanged("Avenue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingName {
            get {
                return this.BuildingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNameField, value) != true)) {
                    this.BuildingNameField = value;
                    this.RaisePropertyChanged("BuildingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FloorNo {
            get {
                return this.FloorNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FloorNoField, value) != true)) {
                    this.FloorNoField = value;
                    this.RaisePropertyChanged("FloorNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HouseNo {
            get {
                return this.HouseNoField;
            }
            set {
                if ((this.HouseNoField.Equals(value) != true)) {
                    this.HouseNoField = value;
                    this.RaisePropertyChanged("HouseNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationCode {
            get {
                return this.LocationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationCodeField, value) != true)) {
                    this.LocationCodeField = value;
                    this.RaisePropertyChanged("LocationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocationType {
            get {
                return this.LocationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationTypeField, value) != true)) {
                    this.LocationTypeField = value;
                    this.RaisePropertyChanged("LocationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parish {
            get {
                return this.ParishField;
            }
            set {
                if ((object.ReferenceEquals(this.ParishField, value) != true)) {
                    this.ParishField = value;
                    this.RaisePropertyChanged("Parish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreAvenue {
            get {
                return this.PreAvenueField;
            }
            set {
                if ((object.ReferenceEquals(this.PreAvenueField, value) != true)) {
                    this.PreAvenueField = value;
                    this.RaisePropertyChanged("PreAvenue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SideFloor {
            get {
                return this.SideFloorField;
            }
            set {
                if ((object.ReferenceEquals(this.SideFloorField, value) != true)) {
                    this.SideFloorField = value;
                    this.RaisePropertyChanged("SideFloor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TownShip {
            get {
                return this.TownShipField;
            }
            set {
                if ((object.ReferenceEquals(this.TownShipField, value) != true)) {
                    this.TownShipField = value;
                    this.RaisePropertyChanged("TownShip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Village {
            get {
                return this.VillageField;
            }
            set {
                if ((object.ReferenceEquals(this.VillageField, value) != true)) {
                    this.VillageField = value;
                    this.RaisePropertyChanged("Village");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zone {
            get {
                return this.ZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ZoneField, value) != true)) {
                    this.ZoneField = value;
                    this.RaisePropertyChanged("Zone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PhoneAddressResult", Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    [System.SerializableAttribute()]
    public partial class PhoneAddressResult : SRL.PostCodeServiceReference.AddressResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrePhoneNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrePhoneNo {
            get {
                return this.PrePhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrePhoneNoField, value) != true)) {
                    this.PrePhoneNoField = value;
                    this.RaisePropertyChanged("PrePhoneNo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataResult", Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    [System.SerializableAttribute()]
    public partial class DataResult : SRL.PostCodeServiceReference.AddressResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrePhoneNoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrePhoneNo {
            get {
                return this.PrePhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PrePhoneNoField, value) != true)) {
                    this.PrePhoneNoField = value;
                    this.RaisePropertyChanged("PrePhoneNo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CertificateResult", Namespace="http://schemas.datacontract.org/2004/07/PostCode.WebServices")]
    [System.SerializableAttribute()]
    public partial class CertificateResult : SRL.PostCodeServiceReference.AddressResult {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificateNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CertificateUrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateNo {
            get {
                return this.CertificateNoField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificateNoField, value) != true)) {
                    this.CertificateNoField = value;
                    this.RaisePropertyChanged("CertificateNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CertificateUrl {
            get {
                return this.CertificateUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.CertificateUrlField, value) != true)) {
                    this.CertificateUrlField = value;
                    this.RaisePropertyChanged("CertificateUrl");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PostCodeServiceReference.IPostCode")]
    public interface IPostCode {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetAddressByPostcode", ReplyAction="http://tempuri.org/IPostCode/GetAddressByPostcodeResponse")]
        SRL.PostCodeServiceReference.AddressResult GetAddressByPostcode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetAddressByPostcode", ReplyAction="http://tempuri.org/IPostCode/GetAddressByPostcodeResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.AddressResult> GetAddressByPostcodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetAddressStringByPostCode", ReplyAction="http://tempuri.org/IPostCode/GetAddressStringByPostCodeResponse")]
        SRL.PostCodeServiceReference.StringResult GetAddressStringByPostCode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetAddressStringByPostCode", ReplyAction="http://tempuri.org/IPostCode/GetAddressStringByPostCodeResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.StringResult> GetAddressStringByPostCodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetPhoneByPostcode", ReplyAction="http://tempuri.org/IPostCode/GetPhoneByPostcodeResponse")]
        SRL.PostCodeServiceReference.PhoneResult GetPhoneByPostcode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetPhoneByPostcode", ReplyAction="http://tempuri.org/IPostCode/GetPhoneByPostcodeResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.PhoneResult> GetPhoneByPostcodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetPositionByPostcode", ReplyAction="http://tempuri.org/IPostCode/GetPositionByPostcodeResponse")]
        SRL.PostCodeServiceReference.PositionResult GetPositionByPostcode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetPositionByPostcode", ReplyAction="http://tempuri.org/IPostCode/GetPositionByPostcodeResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.PositionResult> GetPositionByPostcodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetAddressAndPhoneByPostcode", ReplyAction="http://tempuri.org/IPostCode/GetAddressAndPhoneByPostcodeResponse")]
        SRL.PostCodeServiceReference.PhoneAddressResult GetAddressAndPhoneByPostcode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetAddressAndPhoneByPostcode", ReplyAction="http://tempuri.org/IPostCode/GetAddressAndPhoneByPostcodeResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.PhoneAddressResult> GetAddressAndPhoneByPostcodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetDataByPostcode", ReplyAction="http://tempuri.org/IPostCode/GetDataByPostcodeResponse")]
        SRL.PostCodeServiceReference.DataResult GetDataByPostcode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetDataByPostcode", ReplyAction="http://tempuri.org/IPostCode/GetDataByPostcodeResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.DataResult> GetDataByPostcodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetPostcodeByPhone", ReplyAction="http://tempuri.org/IPostCode/GetPostcodeByPhoneResponse")]
        SRL.PostCodeServiceReference.StringResult GetPostcodeByPhone(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetPostcodeByPhone", ReplyAction="http://tempuri.org/IPostCode/GetPostcodeByPhoneResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.StringResult> GetPostcodeByPhoneAsync(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetAddressByPhone", ReplyAction="http://tempuri.org/IPostCode/GetAddressByPhoneResponse")]
        SRL.PostCodeServiceReference.AddressResult GetAddressByPhone(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetAddressByPhone", ReplyAction="http://tempuri.org/IPostCode/GetAddressByPhoneResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.AddressResult> GetAddressByPhoneAsync(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetPostcodeAndAddressByPhone", ReplyAction="http://tempuri.org/IPostCode/GetPostcodeAndAddressByPhoneResponse")]
        SRL.PostCodeServiceReference.AddressResult GetPostcodeAndAddressByPhone(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetPostcodeAndAddressByPhone", ReplyAction="http://tempuri.org/IPostCode/GetPostcodeAndAddressByPhoneResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.AddressResult> GetPostcodeAndAddressByPhoneAsync(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetPositionByPhone", ReplyAction="http://tempuri.org/IPostCode/GetPositionByPhoneResponse")]
        SRL.PostCodeServiceReference.PositionResult GetPositionByPhone(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetPositionByPhone", ReplyAction="http://tempuri.org/IPostCode/GetPositionByPhoneResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.PositionResult> GetPositionByPhoneAsync(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/ValidatePostCode", ReplyAction="http://tempuri.org/IPostCode/ValidatePostCodeResponse")]
        SRL.PostCodeServiceReference.BooleanResult ValidatePostCode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/ValidatePostCode", ReplyAction="http://tempuri.org/IPostCode/ValidatePostCodeResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.BooleanResult> ValidatePostCodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetDataByCertificateNo", ReplyAction="http://tempuri.org/IPostCode/GetDataByCertificateNoResponse")]
        SRL.PostCodeServiceReference.DataResult GetDataByCertificateNo(string username, string messageHash, string certificateNo, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetDataByCertificateNo", ReplyAction="http://tempuri.org/IPostCode/GetDataByCertificateNoResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.DataResult> GetDataByCertificateNoAsync(string username, string messageHash, string certificateNo, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetActivityCodeByPostCode", ReplyAction="http://tempuri.org/IPostCode/GetActivityCodeByPostCodeResponse")]
        SRL.PostCodeServiceReference.ActivityCodeResult GetActivityCodeByPostCode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetActivityCodeByPostCode", ReplyAction="http://tempuri.org/IPostCode/GetActivityCodeByPostCodeResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.ActivityCodeResult> GetActivityCodeByPostCodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetActivityCodeByPhone", ReplyAction="http://tempuri.org/IPostCode/GetActivityCodeByPhoneResponse")]
        SRL.PostCodeServiceReference.ActivityCodeResult GetActivityCodeByPhone(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetActivityCodeByPhone", ReplyAction="http://tempuri.org/IPostCode/GetActivityCodeByPhoneResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.ActivityCodeResult> GetActivityCodeByPhoneAsync(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GenerateCertificate", ReplyAction="http://tempuri.org/IPostCode/GenerateCertificateResponse")]
        SRL.PostCodeServiceReference.CertificateResult GenerateCertificate(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GenerateCertificate", ReplyAction="http://tempuri.org/IPostCode/GenerateCertificateResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.CertificateResult> GenerateCertificateAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetPostCodeByAddress", ReplyAction="http://tempuri.org/IPostCode/GetPostCodeByAddressResponse")]
        SRL.PostCodeServiceReference.StringResult GetPostCodeByAddress(string username, string messageHash, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetPostCodeByAddress", ReplyAction="http://tempuri.org/IPostCode/GetPostCodeByAddressResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.StringResult> GetPostCodeByAddressAsync(string username, string messageHash, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetWorkshopDataByPostcode", ReplyAction="http://tempuri.org/IPostCode/GetWorkshopDataByPostcodeResponse")]
        SRL.PostCodeServiceReference.WorkshopResult GetWorkshopDataByPostcode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetWorkshopDataByPostcode", ReplyAction="http://tempuri.org/IPostCode/GetWorkshopDataByPostcodeResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.WorkshopResult> GetWorkshopDataByPostcodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetWorkshopDataByPhone", ReplyAction="http://tempuri.org/IPostCode/GetWorkshopDataByPhoneResponse")]
        SRL.PostCodeServiceReference.WorkshopResult GetWorkshopDataByPhone(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPostCode/GetWorkshopDataByPhone", ReplyAction="http://tempuri.org/IPostCode/GetWorkshopDataByPhoneResponse")]
        System.Threading.Tasks.Task<SRL.PostCodeServiceReference.WorkshopResult> GetWorkshopDataByPhoneAsync(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPostCodeChannel : SRL.PostCodeServiceReference.IPostCode, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostCodeClient : System.ServiceModel.ClientBase<SRL.PostCodeServiceReference.IPostCode>, SRL.PostCodeServiceReference.IPostCode {
        
        public PostCodeClient() {
        }
        
        public PostCodeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostCodeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostCodeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostCodeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SRL.PostCodeServiceReference.AddressResult GetAddressByPostcode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetAddressByPostcode(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.AddressResult> GetAddressByPostcodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetAddressByPostcodeAsync(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.StringResult GetAddressStringByPostCode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetAddressStringByPostCode(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.StringResult> GetAddressStringByPostCodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetAddressStringByPostCodeAsync(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.PhoneResult GetPhoneByPostcode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetPhoneByPostcode(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.PhoneResult> GetPhoneByPostcodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetPhoneByPostcodeAsync(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.PositionResult GetPositionByPostcode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetPositionByPostcode(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.PositionResult> GetPositionByPostcodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetPositionByPostcodeAsync(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.PhoneAddressResult GetAddressAndPhoneByPostcode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetAddressAndPhoneByPostcode(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.PhoneAddressResult> GetAddressAndPhoneByPostcodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetAddressAndPhoneByPostcodeAsync(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.DataResult GetDataByPostcode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetDataByPostcode(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.DataResult> GetDataByPostcodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetDataByPostcodeAsync(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.StringResult GetPostcodeByPhone(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetPostcodeByPhone(username, messageHash, preNo, phoneNo, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.StringResult> GetPostcodeByPhoneAsync(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetPostcodeByPhoneAsync(username, messageHash, preNo, phoneNo, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.AddressResult GetAddressByPhone(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetAddressByPhone(username, messageHash, preNo, phoneNo, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.AddressResult> GetAddressByPhoneAsync(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetAddressByPhoneAsync(username, messageHash, preNo, phoneNo, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.AddressResult GetPostcodeAndAddressByPhone(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetPostcodeAndAddressByPhone(username, messageHash, preNo, phoneNo, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.AddressResult> GetPostcodeAndAddressByPhoneAsync(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetPostcodeAndAddressByPhoneAsync(username, messageHash, preNo, phoneNo, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.PositionResult GetPositionByPhone(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetPositionByPhone(username, messageHash, preNo, phoneNo, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.PositionResult> GetPositionByPhoneAsync(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetPositionByPhoneAsync(username, messageHash, preNo, phoneNo, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.BooleanResult ValidatePostCode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.ValidatePostCode(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.BooleanResult> ValidatePostCodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.ValidatePostCodeAsync(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.DataResult GetDataByCertificateNo(string username, string messageHash, string certificateNo, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetDataByCertificateNo(username, messageHash, certificateNo, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.DataResult> GetDataByCertificateNoAsync(string username, string messageHash, string certificateNo, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetDataByCertificateNoAsync(username, messageHash, certificateNo, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.ActivityCodeResult GetActivityCodeByPostCode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetActivityCodeByPostCode(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.ActivityCodeResult> GetActivityCodeByPostCodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetActivityCodeByPostCodeAsync(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.ActivityCodeResult GetActivityCodeByPhone(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetActivityCodeByPhone(username, messageHash, preNo, phoneNo, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.ActivityCodeResult> GetActivityCodeByPhoneAsync(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetActivityCodeByPhoneAsync(username, messageHash, preNo, phoneNo, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.CertificateResult GenerateCertificate(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GenerateCertificate(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.CertificateResult> GenerateCertificateAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GenerateCertificateAsync(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.StringResult GetPostCodeByAddress(string username, string messageHash, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetPostCodeByAddress(username, messageHash, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.StringResult> GetPostCodeByAddressAsync(string username, string messageHash, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetPostCodeByAddressAsync(username, messageHash, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.WorkshopResult GetWorkshopDataByPostcode(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetWorkshopDataByPostcode(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.WorkshopResult> GetWorkshopDataByPostcodeAsync(string username, string messageHash, string postcode, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetWorkshopDataByPostcodeAsync(username, messageHash, postcode, regionCode, nodeCode, clientName);
        }
        
        public SRL.PostCodeServiceReference.WorkshopResult GetWorkshopDataByPhone(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetWorkshopDataByPhone(username, messageHash, preNo, phoneNo, regionCode, nodeCode, clientName);
        }
        
        public System.Threading.Tasks.Task<SRL.PostCodeServiceReference.WorkshopResult> GetWorkshopDataByPhoneAsync(string username, string messageHash, string preNo, string phoneNo, string regionCode, string nodeCode, string clientName) {
            return base.Channel.GetWorkshopDataByPhoneAsync(username, messageHash, preNo, phoneNo, regionCode, nodeCode, clientName);
        }
    }
}
